# Исследование зависимости от заданной размерности и числа обусловленности квадратичных функций

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

In [2]:
from Functions.user_functions import funtion_generator
from Functions.optimization import armijo_grad_descent, conjugate_grad_descent

In [3]:
# Order.
M_SIZE = 10
M_list = np.linspace(2, 11, M_SIZE).astype(int)

# Condition number µ.
CN_SIZE = 10
CN_list = np.linspace(1.0, 19.0, CN_SIZE)

print(M_list)
print(CN_list)

[ 2  3  4  5  6  7  8  9 10 11]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


In [4]:
A_arr = np.empty((M_SIZE,CN_SIZE), dtype=object)
b_arr = np.empty((M_SIZE,CN_SIZE), dtype=object)
#c_arr = np.zeros((M_SIZE,CN_SIZE))
func_arr = np.empty((M_SIZE,CN_SIZE), dtype=object)
grad_func_arr = np.empty((M_SIZE,CN_SIZE), dtype=object)

for m, M_var in enumerate(M_list):
    for k, CN_var in enumerate(CN_list):
        A_arr[m,k], b_arr[m,k], _, func_arr[m,k], grad_func_arr[m,k] = funtion_generator(M=M_var, cond_number=CN_var)

Проверка собственных чисел.

In [5]:
for m, M_var in enumerate(M_list):
    for k, CN_var in enumerate(CN_list):
        eigvals = np.linalg.eigvalsh(A_arr[m,k])
        cond_A = eigvals[-1] / eigvals[0]
        print('Размерность', M_var, ', Собственные числа', eigvals)
        print('Числа обусловленности: заданное <--> вычисленное:\n', CN_var, '<-->', np.round(cond_A,2))

Размерность 2 , Собственные числа [1. 1.]
Числа обусловленности: заданное <--> вычисленное:
 1.0 <--> 1.0
Размерность 2 , Собственные числа [1. 3.]
Числа обусловленности: заданное <--> вычисленное:
 3.0 <--> 3.0
Размерность 2 , Собственные числа [1. 5.]
Числа обусловленности: заданное <--> вычисленное:
 5.0 <--> 5.0
Размерность 2 , Собственные числа [1. 7.]
Числа обусловленности: заданное <--> вычисленное:
 7.0 <--> 7.0
Размерность 2 , Собственные числа [1. 9.]
Числа обусловленности: заданное <--> вычисленное:
 9.0 <--> 9.0
Размерность 2 , Собственные числа [ 1. 11.]
Числа обусловленности: заданное <--> вычисленное:
 11.0 <--> 11.0
Размерность 2 , Собственные числа [ 1. 13.]
Числа обусловленности: заданное <--> вычисленное:
 13.0 <--> 13.0
Размерность 2 , Собственные числа [ 1. 15.]
Числа обусловленности: заданное <--> вычисленное:
 15.0 <--> 15.0
Размерность 2 , Собственные числа [ 1. 17.]
Числа обусловленности: заданное <--> вычисленное:
 17.0 <--> 17.0
Размерность 2 , Собственные чи

In [6]:
x_optim_arr = np.empty((M_SIZE,CN_SIZE), dtype=object)
trajectory_arr = np.empty((M_SIZE,CN_SIZE), dtype=object)
iter_counter_arr = np.zeros((M_SIZE,CN_SIZE))

for m, M_var in enumerate(M_list):
    for k in range(CN_SIZE):
        '''
        x_optim_arr[m,k], trajectory_arr[m,k], iter_counter_arr[m,k], _, _ = armijo_grad_descent(
            loss_func=func_arr[m,k],
            grad_func=grad_func_arr[m,k],
            x_init=np.array([1.5]*M_var),
            lr_multiplier=0.5,
            lr_coeff=0.5, 
            tolerance=1e-3,
            printoutput=False
            )
        '''
        x_optim_arr[m,k], trajectory_arr[m,k], iter_counter_arr[m,k], _, _ = conjugate_grad_descent(
            A=A_arr[m,k],
            b=b_arr[m,k],
            x_init=np.array([1.5]*M_var),
            tolerance=1e-3,
            printoutput=False
            )

ValueError: shapes (1,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
b_arr[0][0]

array([-1.04657235,  0.72955377])

In [8]:
x_init = (np.matrix([1.5]*2)).T
x = x_init.copy()

r = (b_arr[0][0]).T - A_arr[0][0] * x
r_prev = r.copy()
p = r.copy()

learning_rate = ((r.T * r)/(p.T * A_arr[0][0]*p)).item()
print(learning_rate)
x += learning_rate * p
r -= learning_rate * A_arr[0][0] * p
beta = (r.T * r/(r_prev.T * r_prev)).item()
r_prev = r.copy()
p = r + beta * p

r_norm = np.linalg.norm(r, ord=None, axis=None)

0.9999999999999998


Настройки форматирования графиков.

In [ ]:
user_figsize = (10,5)
user_fontsize = 14
user_tickfontsize = 12

In [ ]:
x1_min = -10.0
x1_max = 10.0
x2_min = -10.0
x2_max = 10.0
N = 1000

x = np.empty((2,), dtype=object)
x[0] = np.linspace(x1_min, x1_max, N)
x[1] = np.linspace(x2_min, x2_max, N)
X, Y = np.meshgrid(x[0], x[1])

func_names = [f_well, f_poor, f_rozen]
grad_names = [grad_well, grad_poor, grad_rozen]
func_labels = ['Well-conditioned',
               'Poorly-conditioned',
               'Rosenbrock']

N_FUNC = len(func_names)

Z = np.empty((N_FUNC,), dtype=object)

for k, func in enumerate(func_names):
    Z[k] = func([X, Y])

NameError: name 'f_well' is not defined

In [ ]:
N_METHOD=1
fig, axs = plt.subplots(ncols=N_METHOD, nrows=1, figsize=(6*N_METHOD, 6))
for mdx, ax in enumerate(axs):
    contour = ax.contour(X, Y, z, levels=25, colors='black', alpha=0.5)
    ax.contour(X, Y, z, levels=25, cmap='viridis')
    ax.set_xlabel('$x_1$', fontsize=user_fontsize)
    ax.set_ylabel('$x_2$', fontsize=user_fontsize)
    ax.set_title(method_names[mdx].__name__ + ': ' + str(iter_counter_arr[ndx,mdx]) + ' iterations', fontsize=user_fontsize)
    
    # Подготовка сегментов для LineCollection
    points = np.array([trajectory_arr[ndx,mdx][:, 0], trajectory_arr[ndx,mdx][:, 1]]).T.reshape(-1, 1, 2)
    segments = np.concatenate([points[:-1], points[1:]], axis=1)

    # Создание LineCollection с цветами, зависящими от индекса (шага)
    lc = LineCollection(segments, cmap='RdYlBu_r', linewidth=1.0)
    lc.set_array(np.linspace(0, 1, len(segments)))  # цвет от 0 (начало) до 1 (конец)
    line = ax.add_collection(lc)
    
    # Отмечаем точки
    ax.plot(x_init[0], x_init[1], 'bo', markersize=8, label='Start')
    ax.plot(x_optim_arr[ndx,mdx][0], x_optim_arr[ndx,mdx][1], 'ro', markersize=10, label='End')
        
    ax.tick_params(axis='x', labelsize=user_tickfontsize)
    ax.tick_params(axis='y', labelsize=user_tickfontsize)
    
    ax.legend()
    ax.grid(True, alpha=0.3)

#fig.colorbar(line, ax=axs[ndx], label='Progress from 0 to 1')
plt.tight_layout()
#plt.savefig('readme_img/func_img/trajectory_plots_' + func_lbl + '.png', bbox_inches='tight')
plt.show()

NameError: name 'N_FUNC' is not defined