# Исследование зависимости от заданной размерности и числа обусловленности квадратичных функций

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

In [2]:
cond_number = 5
N = 6
eigvals_float = [np.random.uniform(1.0, cond_number) for _ in range(N)]
eigvals_float

[3.26439907478818,
 3.8889151442030765,
 1.4556276093208287,
 3.574733082817447,
 4.38616782182048,
 1.0703250052005973]

In [3]:
Q, _ = np.linalg.qr(np.random.randn(N, N))  # QR-разложение даёт ортогональную Q
np.round(Q@Q.T,2)
np.round(Q.T@Q,2)

array([[ 1., -0.,  0., -0.,  0., -0.],
       [-0.,  1., -0.,  0., -0., -0.],
       [ 0., -0.,  1., -0., -0., -0.],
       [-0.,  0., -0.,  1.,  0., -0.],
       [ 0., -0., -0.,  0.,  1.,  0.],
       [-0., -0., -0., -0.,  0.,  1.]])

In [4]:
np.random.randn(N)

array([ 0.17865299, -1.58779784,  0.5752956 , -1.1490773 , -0.82708734,
       -1.36321436])

In [5]:
from Functions.user_functions import funtion_generator
from Functions.optimization import const_step_grad_descent, armijo_grad_descent, steepest_grad_descent

In [6]:
A,b,c,func,grad_func = funtion_generator(N=2, cond_number=2.0)

In [7]:
# Проверка
eigvals = np.linalg.eigvalsh(A)
cond_A = eigvals[-1] / eigvals[0]
print(f"Собственные числа: {eigvals}")
print(f"Число обусловленности: {cond_A:.2f}")

Собственные числа: [1. 2.]
Число обусловленности: 2.00


In [8]:
func(np.array([0.3,1.4]))

56.99056977504434

In [9]:
x_optim, trajectory, iter_counter, _, _ = armijo_grad_descent(
                    loss_func=func,
                    grad_func=grad_func,
                    x_init=np.array([-2.2, 1.1]),
                    lr_multiplier=0.5,
                    lr_coeff=0.5, 
                    tolerance=1e-3,
                    printoutput=False
                    )

In [10]:
x_optim

array([ 0.92505704, -0.52731958])

In [ ]:
N_METHOD=1
    fig, axs = plt.subplots(ncols=N_METHOD, nrows=1, figsize=(6*N_METHOD, 6))
    for mdx, ax in enumerate(axs):
        contour = ax.contour(X, Y, z, levels=25, colors='black', alpha=0.5)
        ax.contour(X, Y, z, levels=25, cmap='viridis')
        ax.set_xlabel('$x_1$', fontsize=user_fontsize)
        ax.set_ylabel('$x_2$', fontsize=user_fontsize)
        ax.set_title(method_names[mdx].__name__ + ': ' + str(iter_counter_arr[ndx,mdx]) + ' iterations', fontsize=user_fontsize)
        
        # Подготовка сегментов для LineCollection
        points = np.array([trajectory_arr[ndx,mdx][:, 0], trajectory_arr[ndx,mdx][:, 1]]).T.reshape(-1, 1, 2)
        segments = np.concatenate([points[:-1], points[1:]], axis=1)

        # Создание LineCollection с цветами, зависящими от индекса (шага)
        lc = LineCollection(segments, cmap='RdYlBu_r', linewidth=1.0)
        lc.set_array(np.linspace(0, 1, len(segments)))  # цвет от 0 (начало) до 1 (конец)
        line = ax.add_collection(lc)
        
        # Отмечаем точки
        ax.plot(x_init[0], x_init[1], 'bo', markersize=8, label='Start')
        ax.plot(x_optim_arr[ndx,mdx][0], x_optim_arr[ndx,mdx][1], 'ro', markersize=10, label='End')
            
        ax.tick_params(axis='x', labelsize=user_tickfontsize)
        ax.tick_params(axis='y', labelsize=user_tickfontsize)
        
        ax.legend()
        ax.grid(True, alpha=0.3)

    #fig.colorbar(line, ax=axs[ndx], label='Progress from 0 to 1')
    plt.tight_layout()
    plt.savefig('readme_img/func_img/trajectory_plots_' + func_lbl + '.png', bbox_inches='tight')
    plt.show()

NameError: name 'N_FUNC' is not defined